# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/campusconnect_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


# JWT Settings
campusconnect.jwt.secret=NDQxZGE1YWI1YTdhM2M5MGJhZDA2ZDdlNGNlMzBmMTViOWRiZjBjNzhjYTc2NzllOTI1M2NkYzk4MWIzMzY4Ng==
campusconnect.jwt.expiration=86400000

# Server settings
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manojalluri2727@gmail.com
spring.mail.password=myqjtrdzirymiuqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
